name: Selenium Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Allows GitHub Actions to commit & push changes

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug: List Files in the Runner
        run: ls -R  # Check project structure

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver

      - name: Run Maven Tests
        run: mvn clean test

      # Step 1: Force Git to detect changes
      - name: Force Git to Detect Changes
        run: |
          git update-index --refresh
          git status

      # Step 2: Debug if Excel file was updated
      - name: Debug: Check If Excel File Was Updated
        run: |
          ls -lah path/to/excel-file.xlsx
          md5sum path/to/excel-file.xlsx || echo "File does not exist"

      # Step 3: Set up Git user details
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Step 4: Commit & Push changes
      - name: Commit and Push Excel File Changes
        run: |
          git add path/to/excel-file.xlsx
          git status  # Verify if the file is staged
          git commit -m "Update Excel file after test run" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
