name: Selenium Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Project Structure
      run: ls -R   # Debugging step to check where pom.xml is located

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Chrome & ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y chromium-chromedriver

    - name: Navigate to the Correct Directory
      run: cd SampleProject  # Change this if pom.xml is inside a different folder

    - name: Run Maven Tests
      run: mvn clean test
