name: Selenium Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug: List Files in the Runner
        run: ls -R  # Check the project structure in GitHub Actions

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Verify POM File Exists
        run: |
          if [ ! -f pom.xml ]; then
            echo "Error: pom.xml
