name: Selenium Test Automation

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests
  workflow_dispatch:  # Allows manual triggering

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Chrome & ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y chromium-chromedriver

    - name: Set up Maven
      run: mvn -version

    - name: Run Selenium Tests
      run: mvn clean test
